### ISSUE TITLE
Change the color of the icon for already pinned urls

### ISSUE THREAD

**Issue by lucazav** [mariofink/epic-pinboard#11]
It'd be really useful to have the pin icon colored in gray if the bookmark isn't pinned yet, and in blue if it's already pinned

**Comment by mariofink** [comment]
Great idea. Working on this right now. Should be ready soon 🤞

**Comment by mariofink** [comment]
This is now available in version 1.0.3 that just got released: https://addons.mozilla.org/en-US/firefox/addon/epic-pinboard/

**Comment by mariofink** [comment]
Good point. Fixed that in the the latest version 1.0.5.
