### ISSUE TITLE
Focus the tags field by default

### ISSUE THREAD

**Issue by autonome** [mariofink/epic-pinboard#9]
When saving URLs, I have to manually click the tags field to add tags.

If that field was focused by default, the interaction flow would be smoother. Lots of other Pinboard extensions do this, and I think the official bookmarklet does also.

My flow would then be almost as frictionless as can be:

* keyboard shortcut
* type tags
* hit enter
* voila!

**Comment by mariofink** [comment]
I totally missed this feature request! Just discovered it yesterday. 
So obvious when you think about it 😅 – and now implemented in version 1.0.9
